/**
 * Truck Record Management - Text Strings
 * Easily modify these values to change the visible text, labels, and placeholders in the application.
 */

export const STRINGS = {
  appTitle: "Stock Record Management",
  appSubtitle: "Manage logistics operations, truck loads, and warehouse routing with ease.",
  
  // Table Columns
  cols: {
    no: "No",
    date: "Date",
    truckNumber: "Truck Number",
    owner: "Owner",
    size: "Size",
    weight: "Weight",
    warehouseNumber: "Warehouse Number",
    actions: "Actions"
  },
  
  // Adding records form
  addRecordForm: {
    title: "Add New Truck Record",
    dateLabel: "Date",
    selectTruck: "-- Select Truck Number --",
    selectOwner: "-- Select Owner --",
    selectSize: "-- Select Size --",
    selectWeight: "-- Select Weight --",
    selectWarehouse: "-- Select Warehouse --",
    submitBtn: "Add Record",
    updatingBtn: "Updating...",
    editTitle: "Edit Truck Record",
    saveChangeBtn: "Save Changes",
    cancelBtn: "Cancel"
  },

  // Dropdown Management forms under the table
  addDropdownOptionsForm: {
    title: "Add Dropdown Options",
    subtitle: "Add custom items to your select menus. Any added values immediately expand the dropdown lists above.",
    truckLabel: "Add Truck Number",
    ownerLabel: "Add Owner",
    sizeLabel: "Add Size",
    weightLabel: "Add Weight",
    warehouseLabel: "Add Warehouse Number",
    inputTruckPlaceholder: "e.g., TRK-999",
    inputOwnerPlaceholder: "e.g., Prime Fast Cargo",
    inputSizePlaceholder: "e.g., 53-footer Reefer",
    inputWeightPlaceholder: "e.g., 18.2 Tons",
    inputWarehousePlaceholder: "e.g., WH-F6",
    submitBtn: "Add Option"
  },

  // Filters section
  filters: {
    title: "Filter & Search Records",
    noPlaceholder: "Search No (e.g. 1)...",
    startDateLabel: "Start Date",
    endDateLabel: "End Date",
    allTrucks: "All Truck Numbers",
    allOwners: "All Owners",
    allSizes: "All Sizes",
    allWeights: "All Weights",
    allWarehouses: "All Warehouse Numbers",
    clearFiltersBtn: "Clear Filters",
    noRecordsFound: "No matching truck records found."
  },

  // Notifications & Confirmations
  notifications: {
    addRecordSuccess: "Truck record added successfully!",
    updateRecordSuccess: "Truck record updated successfully!",
    deleteRecordSuccess: "Truck record deleted successfully!",
    addOptionSuccess: "New option '{val}' added to {category}!",
    invalidDate: "Please select a valid date.",
    duplicateOption: "This option already exists in the dropdown list.",
    fillRequiredFields: "Please fill out all fields in the record form.",
    fillOptionField: "Please enter a value to append.",
    deleteConfirm: "Are you sure you want to delete this truck record? This action cannot be reversed.",
    supabaseError: "Error connecting to Supabase: {error}",
    localModeActive: "Database not connected. Using browser LocalStorage fallback so everything still functions!",
    syncingText: "Syncing data...",
    loadingText: "Loading data from database..."
  },

  // Supabase Setup guide text
  supabaseSetupGuide: {
    title: "Supabase Postgres Database Setup Guide",
    intro: "To set up database storage on your Supabase dashboard, paste and run these SQL queries in your Supabase SQL Editor:",
    recordsSql: `-- 1. Create a table for truck records
CREATE TABLE IF NOT EXISTS public.truck_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    record_date DATE NOT NULL,
    truck_number TEXT NOT NULL,
    owner TEXT NOT NULL,
    size TEXT NOT NULL,
    weight TEXT NOT NULL,
    warehouse_number TEXT NOT NULL
);

-- Enable Row Level Security (RLS) and allow public anonymous access for this app
ALTER TABLE public.truck_records ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.truck_records FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON public.truck_records FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access" ON public.truck_records FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access" ON public.truck_records FOR DELETE USING (true);
`,
    optionsSql: `-- 2. Create a table for dynamic dropdown options
CREATE TABLE IF NOT EXISTS public.dropdown_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    category TEXT NOT NULL, -- 'truck_number', 'owner', 'size', 'weight', 'warehouse_number'
    value TEXT NOT NULL,
    CONSTRAINT unique_category_value UNIQUE (category, value)
);

-- Enable RLS and allow public anonymous access
ALTER TABLE public.dropdown_options ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.dropdown_options FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON public.dropdown_options FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete access" ON public.dropdown_options FOR DELETE USING (true);
`,
    seedSql: `-- 3. [Optional] Seed initial default values for dropdowns
INSERT INTO public.dropdown_options (category, value) VALUES
('truck_number', 'TRK-001'), ('truck_number', 'TRK-002'), ('truck_number', 'TRK-003'), ('truck_number', 'TRK-004'), ('truck_number', 'TRK-005'),
('owner', 'John Doe Logistics'), ('owner', 'Smith Transport'), ('owner', 'Global Freighters'), ('owner', 'Apex Movers'), ('owner', 'Express Shipping'),
('size', '10-footer'), ('size', '20-footer'), ('size', '40-footer'), ('size', 'Flatbed'), ('size', 'Reefer'),
('weight', '5.5 Tons'), ('weight', '10 Tons'), ('weight', '15 Tons'), ('weight', '20.5 Tons'), ('weight', '25 Tons'),
('warehouse_number', 'WH-A1'), ('warehouse_number', 'WH-B2'), ('warehouse_number', 'WH-C3'), ('warehouse_number', 'WH-D4'), ('warehouse_number', 'WH-E5')
ON CONFLICT (category, value) DO NOTHING;`,
    doneMsg: "Once these tables are created, all operations (Add, Edit, Delete, Options Addition) will read and write to Supabase permanently. If the tables do not exist yet, the application gracefully falls back to browser LocalStorage automatically."
  }
};
